version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v2"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "PyInstaller"
      - dependency-name: "flit_core"
      - dependency-name: "colorama"
      - dependency-name: "docutils"
      - dependency-name: "cryptography"
      - dependency-name: "awscrt"
      - dependency-name: "ruamel.yaml"
      - dependency-name: "ruamel.yaml.clib"
      - dependency-name: "prompt-toolkit"
      - dependency-name: "distro"
      - dependency-name: "python-dateutil"
      - dependency-name: "jmespath"
      - dependency-name: "urllib3"
