---
name: "Source distribution issue"
description: Report an issue with source distribution
title: "(short issue description)"
labels: [source-distribution, needs-triage]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: What is the problem? A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        All of the commands, arguments and their outputs used when trying to build the AWS CLI. Anything else that might be relevant for troubleshooting this issue.
    validations:
      required: false
  - type: input
    id: sdk-version
    attributes:
      label: CLI version used
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment details (OS name and version, etc.)
    validations:
        required: true
